### ISSUE TITLE
Deep index.cjs imports required after 1.1.20?

### ISSUE THREAD

**Issue by samsargent** [Runware/sdk-js#17]
👋 @YomiCasual Since updating to >1.1.20 we've had to change imports in our app from `from @runware/sdk-js` to `from @runware/sdk-js/dist/index.cjs`

Was that expected, I suspect it's maybe related to adding `tsup`? 🤔

**Comment by YomiCasual** [comment]
@samsargent 

I am wondering why your import has to changed

tsup bundler now generates cjs instead of mjs, but it shouldn't still affect your import.

Can you provide any further insight into why you might be having this?

**Comment by samsargent** [comment]
I'm not sure, was hoping you might know haha!

After some quick googling, this seems like it might be related? 🤷‍♂️ 
https://github.com/egoist/tsup/issues/953

**Comment by YomiCasual** [comment]
@samsargent 

Thanks for this. Is this a breaking change you will like us to look into or you can live with importing from the `cjs`.

**Comment by YomiCasual** [comment]
@samsargent , I have published a new version to fix this with from `@runware/sdk-js@1.1.26`. You should be able to import directly

**Comment by samsargent** [comment]
Thanks @YomiCasual! I'll give that a test today. Is there another repo with those latest changes? I'm curious what the fix was...

**Comment by YomiCasual** [comment]
@samsargent. It is this same repo. You can check the last commit on main related to package.json.

Let me know if this works, so we can close this issue.
Thanks.

**Comment by samsargent** [comment]
ah, looks like I added that comment just before it merged. All good, confirming it's fixed now 😄
