### ISSUE TITLE
Model Upload Types?

### ISSUE THREAD

**Issue by samsargent** [Runware/sdk-js#18]
Have just been testing the model upload api, I think there are a few discrepancies between the types and the docs...

`TAddModelCheckPoint`
`defaultScheduler?:number` - I think this should be a string, and it also looks required? I can make a quick PR for this but there may be others. Docs do say 'If not specified, the model will use the scheduler it was trained with." but it errors if you leave it off:
`Invalid value for defaultScheduler parameter. Default scheduler must be a string value representing a valid scheduler. Supported values can be found in documentation.',\n    parameter: 'defaultScheduler',\n    type: 'string',\n    documentation: 'https://docs.runware.ai/en/image-inference/schedulers#supported-schedulers`

Also seems like `type: EModelType;` should be required.

**Comment by YomiCasual** [comment]
@samsargent 

I have updated this. Please update and check if this has been resolved.

Thanks for always pointing out these issues to better our sdk 🫡

**Comment by YomiCasual** [comment]
I saw that you created an MR @samsargent 
https://github.com/Runware/sdk-js/pull/19

I'm just seeing this.

Thanks for the contribution
