### ISSUE TITLE
Any other models besides runware:100@1 are NOT working. 

### ISSUE THREAD

**Issue by ezam0000** [Runware/sdk-js#4]
The problem may be API issues, especially when there is no server status; it always says " all services operational,"  but that is never the case. 

Loras and SDXL or SD 1.5 models have stopped working for the last  12 hours.  

This example worked last night, and  when trying to request  again today, it is not working and returns error 500:

From RUNWARE submitted request:

{1 item
"0":{16 items
"taskType":string"imageInference"
"model":string"civitai:277058@646523"
"positivePrompt":string"cctvfootage aerial view of a rally car crashing through shelves at the grocery store, action shot, motion blur, chaos, debris flying everywhere"
"negativePrompt":string"low saturation"
"height":int1024
"width":int1536
"numberResults":int1
"lora":[1 item
0:{2 items
"model":string"civitai:178910@200827"
"weight":int1
}
]
"outputType":string"URL"
"outputFormat":string"WEBP"
"CFGScale":int5
"steps":int28
"seed":float34304270473141
"scheduler":string"default"
"includeCost":booltrue
"taskUUID":string"67f2ed9e-0b12-4988-ace5-046ba2ef0af3"
}
}

**Comment by YomiCasual** [comment]
@ezam0000 

Are you still experiencing this issue and can you please properly format the submitted request if you are still experiencing this?

**Comment by ezam0000** [comment]
> @ezam0000
> 
> Are you still experiencing this issue and can you please properly format the submitted request if you are still experiencing this?

It's working now with different models and Lora . 
I haven't tired any Lora for runware:01 model yet ( Don't see any documentation on flux Lora support)

**Comment by YomiCasual** [comment]
@ezam0000 

We don’t support FLUX LoRA yet in production but we plan a release on Monday.

Let me know if I can close this issue if you don't have any other blockers.

Thanks.

**Comment by YomiCasual** [comment]
All issues resolved
