### ISSUE TITLE
Prompt enhancer not working 

### ISSUE THREAD

**Issue by ezam0000** [Runware/sdk-js#5]
It worked for a few hours and never again. Please add the status for the API request properties, as there is a 500 error.

**Comment by YomiCasual** [comment]
@ezam0000 

Are you still experiencing this issue?

**Comment by ezam0000** [comment]
> @ezam0000
> 
> Are you still experiencing this issue?

Yes, it's never worked after the first days the api released .

**Comment by YomiCasual** [comment]
@ezam0000
Sorry for the inconvenience but this is currently working in production now. 

Please confirm it and let me know if I can close this issue if there are not other blockers.

Thanks.

**Comment by YomiCasual** [comment]
All issues resolved
