### ISSUE TITLE
Demo does not work and is of a different SDK

### ISSUE THREAD

**Issue by CyrusVorwald** [Runware/sdk-js#7]
The demo listed at https://github.com/Runware/sdk-js?tab=readme-ov-file#demo uses picfinder-sdk. If I fork it, add my API key, type in a prompt, and hit the Get Images button, it seems to be stuck loading for a long time until eventually showing error "Message could not be received for getting images".

Also, doesn't the RunwareClient expose the API key to the client?

**Comment by chris-anstey-runware** [comment]
Hi there - the first issue should be fixed now.

As for the second issue, if you were to run this client side on a public website, yes, you would be exposing your API key to the public. The system is designed to be run either from server-side, or in a private environment if you wanted to run the SDK in the browser.
