### ISSUE TITLE
Bug with 'SHOULD_RETRY' in retrying connection code

### ISSUE THREAD

**Issue by chris-anstey-runware** [Runware/sdk-js#8]
It looks like there is a bug in the `ensureConnection()` function, in particular with [the `SHOULD_RETRY` value](https://github.com/Runware/sdk-js/blob/b28f3f386d8cee4d83a50df24e10ff0a5058601a/Runware/Runware-base.ts#L933). When it is set, `retry` has just been set to `0`, so `SHOULD_RETRY` will never be `true`, and we'll never retry the connection.

```
        let retry = 0;
        const MAX_RETRY = 30;
        const SHOULD_RETRY = 30 / 2 === retry;
...
                if (SHOULD_RETRY) {
                  this.connect();
                }
```

As the code is in the Retry Interval, I'd suggest we don't even need a "should retry" check? We can just retry every time?

**Comment by gorantosicpf** [comment]
fixed here: https://github.com/Runware/sdk-js/pull/10
